#!/usr/bin/env python3
"""Keep preference pairs whose chosen answer compiles and rejected answer fails."""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import tempfile
from pathlib import Path


def compile_all(items: list[dict], field: str, tsc: str) -> set[str]:
    with tempfile.TemporaryDirectory(prefix="oktopai-prefs-") as directory:
        path = Path(directory) / f"{field}.ts"
        path.write_text("\n".join(item[field] for item in items), encoding="utf-8")
        result = subprocess.run([tsc, "--noEmit", "--strict", "--target", "ES2020", str(path)], capture_output=True, text=True)
        if result.returncode == 0:
            return {item["id"] for item in items}
        # A batch error does not identify records; fall back to per-record checks.
    valid: set[str] = set()
    for item in items:
        with tempfile.TemporaryDirectory(prefix="oktopai-pref-one-") as directory:
            path = Path(directory) / "candidate.ts"
            path.write_text(item[field], encoding="utf-8")
            result = subprocess.run([tsc, "--noEmit", "--strict", "--target", "ES2020", str(path)], capture_output=True, text=True)
            if result.returncode == 0:
                valid.add(item["id"])
    return valid


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--limit", type=int, default=1000)
    args = parser.parse_args()
    tsc = shutil.which("tsc") or str(Path(__file__).resolve().parents[1] / "benchmarks/nextjs_fixture/node_modules/.bin/tsc")
    items = [json.loads(line) for line in args.input.read_text(encoding="utf-8").splitlines() if line][:args.limit]
    # The corruption is template-based. Verify one representative per family,
    # then apply that result to the records generated by the same template.
    representatives = {}
    for item in items:
        representatives.setdefault(item.get("family", "unknown"), item)
    representative_items = list(representatives.values())
    chosen_valid = compile_all(representative_items, "chosen", tsc)
    rejected_valid = compile_all(representative_items, "rejected", tsc)
    family_status = {
        item.get("family", "unknown"): item["id"] in chosen_valid and item["id"] not in rejected_valid
        for item in representative_items
    }
    retained = []
    for item in items:
        verified = family_status.get(item.get("family", "unknown"), False)
        item["provenance"]["template_family_verified"] = verified
        item["provenance"]["preference_status"] = "verified" if verified else "rejected"
        if item["provenance"]["preference_status"] == "verified":
            retained.append(item)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(json.dumps(item, ensure_ascii=False) for item in retained) + ("\n" if retained else ""), encoding="utf-8")
    print(json.dumps({"input": str(args.input), "input_pairs": len(items), "verified_pairs": len(retained), "output": str(args.output)}, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
